### ISSUE TITLE
About Time-LLM FT

### ISSUE THREAD

**Issue by zachysun** [UConn-DSIS/Empowering-Time-Series-Analysis-with-LLM#1]
Thanks for this work.

I think Time-LLM seems not to fine-tune the LLM backbone.

> "Time-LLM is a reprogramming framework to repurpose LLMs for general time series forecasting with the backbone language models kept intact."

https://github.com/KimMeen/Time-LLM

**Comment by UConn-DSIS** [comment]
Thanks a lot for catching that!

Yes, you are right. We will update it accordingly in the final version.
